import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
/*
Jet Black
#2D3142

Blue Slate
#4F5D75

Lighter grey
#424e63ff

Bg color
#2c384dff

Silver
#BFC0C0

White 
#FFFFFF

Coral Glow
#EF8354
*/

export const metadata: Metadata = {
	title: "Kasane Teto",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable} bg-[#4F5D75]`} lang="en">
			
			<div className="bg-[#2D3142]">Test</div>

			<body className="">{children}</body>
		</html>
	);
}
