import "~/styles/globals.css";
import Link from 'next/link'

import type { Metadata } from "next";
import { Geist } from "next/font/google";
/*
Jet Black
#2D3142

Blue Slate
#4F5D75

Lighter grey
#424e63ff

Bg color
#2c384dff

Silver
#BFC0C0

White 
#FFFFFF

Coral Glow
#EF8354
*/

export const metadata: Metadata = {
	title: "Kasane Teto",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable} bg-[#2c384dff]`} lang="en">
			<div className="container py-8">
				<header className="fixed top-0 bg-[#2D3142] z-50 w-full px-5 py-4 flex justify-between items-center ">
					<div className="text-lg">
						<Link className="text-white px-3 rounded " href="/">Home</Link>
							
						<Link className="text-white px-3 rounded" href="/database">Database</Link>
					</div>		
				</header>
			</div>	
				<main className="">
					{children}
				</main>
		
		</html>
	);
}
